///* BASIC_CONSTANTS
// * Author: T0164919
// * Creation date: 7/30/2015
// */
//MACHINE
//    BASIC_CONSTANTS
//SETS
//    BOOL = {FALSE,TRUE}
//CONSTANTS
//    minint,maxint,INT,NAT,INT1,NAT1,CHAR
//PROPERTIES
//    minint : INTEGER &
//    maxint : NATURAL &
//    minint < 0 &
//    maxint > 0 &
//    INT = minint..maxint &
//    NAT = 0..maxint &
//    NAT1 = 1..maxint &
//    INT1 minint..-1 &
//    CHAR = 0..255
//    
//END
//